version: '3'

services:
  extraction:
    image: image-extraction
    container_name: extraction_container
    volumes:
      - ./app/data:/data
    ports:
      - 9999:9999
    networks:
      - app_network

  transformation:
    image: image-transformation
    container_name: transformation_container
    volumes:
      - ./app/data:/data
    ports:
      - 8888:8888
    networks:
      - app_network
    depends_on:
      - extraction

volumes:
  data:

networks:
  app_network:
    driver: bridge
