FROM python:3.9

# répertoire de travail dans le conteneur
WORKDIR /app

# Copie du fichier de dépendances
COPY requirements.txt .

# Installation des dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copie du script d'extraction
COPY src/scripts/load/L7.py src/scripts/load/


# Exécution du script
CMD ["python", "src/scripts/load/L7.py"]
