version: '3.8'

services:
  extraction:
    image: image-extraction
    container_name: extraction
    volumes:
      - ./app/data:/data
    ports:
      - 8000:8000
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  transformation:
    image: image-transformation
    container_name: transformation
    volumes:
      - ./app/data:/data
    ports:
      - 8888:8888
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 20s
      retries: 10
    depends_on:
      extraction:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - app_network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=jben
      - ELASTICSEARCH_PASSWORD=4862
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5601/api/status || exit 1"]
      interval: 1m
      timeout: 20s
      retries: 10

  loading:
    image: image-loading
    container_name: loading
    volumes:
      - ./app/data:/data
    ports:
      - 7777:7777
    networks:
      - app_network
    depends_on:
      kibana:
        condition: service_healthy
      transformation:
        condition: service_healthy

volumes:
  data:
  esdata:
    driver: local

networks:
  app_network:
    driver: bridge