FROM python:3.9-slim


WORKDIR /arch
RUN apt-get update && apt-get install -y curl


COPY requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt


COPY src/scripts/archive/A0.py src/scripts/archive/
COPY src/scripts/archive/data/archive_raw.csv /arch/


# Définition de la commande pour exécuter le script wrapper et le serveur FastAPI
CMD ["sh", "-c", "python src/scripts/archive/A0.py"]