FROM python:3.9-slim


WORKDIR /app
COPY requirements.txt .


RUN python -m pip install --no-cache-dir -r requirements.txt


COPY src/scripts/load/L0.py src/scripts/load/
COPY src/scripts/load/wrapper_loading.py src/scripts/load/


RUN chmod +x src/scripts/load/wrapper_loading.py

# Définition de la commande pour exécuter le script wrapper
CMD ["python", "src/scripts/load/wrapper_loading.py"]